# Generated by Django 5.0.3 on 2024-05-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarifas_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('propietario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavadero', models.BooleanField(default=False)),
                ('cochera', models.BooleanField(default=False)),
                ('fecha_hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo', models.CharField(blank=True, max_length=20, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavado.conductor')),
                ('tarifa_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas_vehiculos.tarifavehiculo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavado.vehiculo')),
            ],
        ),
    ]
