# Generated by Django 5.0.3 on 2024-05-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavanderia',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='lavanderia',
            name='tiempo',
        ),
        migrations.RemoveField(
            model_name='lavanderia',
            name='tipo_vehiculo',
        ),
    ]
