# Generated by Django 5.0.3 on 2024-06-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='serie',
        ),
    ]
