# Generated by Django 5.0.3 on 2024-05-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavanderia',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
