# Generated by Django 5.0.3 on 2024-05-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0002_lavanderia_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavanderia',
            old_name='precio',
            new_name='precio_cochera',
        ),
    ]
