# Generated by Django 5.0.3 on 2024-05-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0003_rename_precio_lavanderia_precio_cochera'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavanderia',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
