# Generated by Django 5.0.3 on 2024-05-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0004_lavanderia_fecha_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavanderia',
            name='efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lavanderia',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
