# Generated by Django 5.0.3 on 2024-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0005_lavanderia_efectivo_lavanderia_vuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavanderia',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('terminada', 'Terminada')], default='en_proceso', max_length=20),
        ),
    ]
