# Generated by Django 5.0.3 on 2024-05-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0007_lavanderia_caja_cerrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavanderia',
            old_name='caja_cerrada',
            new_name='nombre_caja_cerrada',
        ),
    ]
