# Generated by Django 5.0.3 on 2024-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0010_remove_lavanderia_nombre_caja_cerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavanderia',
            name='caja_cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
