# Generated by Django 5.0.3 on 2024-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0011_lavanderia_caja_cerrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavanderia',
            name='caja_cerrada',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('terminada', 'Terminada')], default='abierto', max_length=20),
        ),
    ]
