# Generated by Django 5.0.3 on 2024-06-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado', '0014_alter_lavanderia_caja_cerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavanderia',
            name='codigo_barras',
            field=models.ImageField(blank=True, upload_to='codigos_barras/'),
        ),
    ]
