# Generated by Django 5.0.3 on 2024-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('Automóvil', 'Automóvil'), ('Camioneta', 'Camioneta'), ('Moto', 'Moto')], max_length=100, unique=True)),
                ('precio_manana', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_tarde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_dia_completo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_lavado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
