# Generated by Django 5.0.3 on 2024-05-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifavehiculo',
            name='precio_cochera',
        ),
    ]
