# Generated by Django 5.0.3 on 2024-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lavanderia', 'Lavandería'), ('cochera', 'Cochera')], max_length=10)),
                ('fecha_hora_transaccion', models.DateTimeField(auto_now_add=True)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cerrada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCierreCajaCochera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_transaccion', models.DateTimeField(auto_now_add=True)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCierreCajaLavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_transaccion', models.DateTimeField(auto_now_add=True)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
