# Generated by Django 5.0.3 on 2024-05-23 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lavado', '0006_lavanderia_estado'),
        ('tarifas_vehiculos', '0002_remove_tarifavehiculo_precio_cochera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lavanderia', 'Lavandería'), ('cochera', 'Cochera')], max_length=10)),
                ('fecha_hora_transaccion', models.DateTimeField(auto_now_add=True)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cerrada', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lavado.conductor')),
                ('lavanderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavado.lavanderia')),
                ('tarifa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarifas_vehiculos.tarifavehiculo')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lavado.vehiculo')),
            ],
        ),
    ]
