# Generated by Django 5.0.3 on 2024-07-01 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocierrecajacochera',
            name='tipo_usuario',
            field=models.CharField(default='adm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrocierrecajacochera',
            name='usuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
