# Generated by Django 5.0.3 on 2024-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_caja_nombre_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocierrecajalavanderia',
            name='nombre_caja',
            field=models.CharField(default='caja 1', max_length=100),
            preserve_default=False,
        ),
    ]
