# Generated by Django 5.0.3 on 2024-05-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_registrocierrecajalavanderia_nombre_caja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='nombre_caja',
            new_name='nombre_caja_cerrada',
        ),
    ]
