# Generated by Django 5.0.3 on 2024-05-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_alter_caja_nombre_caja_cerrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocierrecajalavanderia',
            old_name='nombre_caja',
            new_name='nombre_caja_cerrada',
        ),
    ]
