# Generated by Django 5.0.3 on 2024-05-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_rename_nombre_caja_registrocierrecajalavanderia_nombre_caja_cerrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='nombre_caja_cerrada',
        ),
        migrations.RemoveField(
            model_name='registrocierrecajalavanderia',
            name='nombre_caja_cerrada',
        ),
    ]
